### ISSUE TITLE
[FEATURE REQUEST] Generate README.md

### ISSUE THREAD

**Issue by fuhlig** [baerkins/vscode-fractal-folder#1]
Proposal:
When creating a new folder, an (optional) `README.md` is created. 
This gets picked up by Fractal to generate documentation and show inside the `Notes` panel.
See [Fractal documentation](https://fractal.build/guide/components/notes.html#the-readme-md-file).

Thanks in advance for considering : )

**Comment by baerkins** [comment]
Good idea, will add!

**Comment by baerkins** [comment]
Closed in 069bc48
