### ISSUE TITLE
[FEATURE REQUEST] Extend SCSS option

### ISSUE THREAD

**Issue by Dan9boi** [baerkins/vscode-fractal-folder#3]
Could you change so that we can write the extention of the style - for making it even more usable.

Ideas for extentions is:
- CSS
- PCSS
- LESS
- STYL

**Comment by baerkins** [comment]
Version 0.1.0 has a Custom Extensions option (sass option is removed), where you can add a comma separated list of extensions for file generation! Hope that helps - and thanks for the feedback!
